---
label: Recipe
hide_body: true
display_field: title
fields:
- name: layout
  type: text
  config:
    required: true
  label: Layout
  default: Recipe
  hidden: true
- name: title
  type: text
  config:
    required: true
  label: Title
- name: description
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: image
  type: file
  config:
    maxSize: 250
  label: Image
- name: ingredients
  type: field_group_list
  fields:
  - name: name
    type: text
    config:
      required: true
    label: Name
  - name: quantity
    type: text
    config:
      required: true
    label: Quantity
  - name: notes
    type: text
    config:
      required: false
    label: Notes
  - name: image
    type: file
    config:
      maxSize: 250
    label: Image
  config:
    min: 
    max: 
    labelField: 
  label: Ingredients
- name: steps
  type: field_group_list
  fields:
  - name: title
    type: text
    config:
      required: false
    label: Title
  - name: description
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: false
      schema:
        format: markdown
    label: Description
  - name: time
    type: text
    config:
      required: false
    label: Time
  - name: image
    type: file
    config:
      maxSize: 250
    label: Image
  config:
    min: 
    max: 
    labelField: 
  label: Steps
pages:
- _posts/2019-12-06-pane.md
- _posts/lenticchie-paprika-e-peperoncino.md
