---
label: Recipe
hide_body: true
display_field: title
fields:
- name: layout
  type: select
  default: Recipe
  config:
    required: true
    options:
    - Post
    - Recipe
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Layout
  hidden: true
- name: title
  type: text
  config:
    required: true
  label: Title
- name: image
  type: file
  config:
    maxSize: 250
  label: Image
- name: description
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: ingredients
  type: blocks
  label: Ingredients
  template_types:
  - ingredients
  config:
    min: 
    max: 
- name: process
  type: blocks
  label: Process
  template_types:
  - process
  config:
    min: 
    max: 
pages:
- _posts/pizza.md
- _posts/bagels.md
- _posts/2019-12-05-pane.md
