---
label: Recipe
hide_body: true
display_field: title
fields:
- name: layout
  type: select
  default: Recipe
  config:
    required: true
    options:
    - Post
    - Recipe
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Layout
  hidden: true
- name: title
  type: text
  config:
    required: true
  label: Title
- name: description
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: image
  type: file
  config:
    maxSize: 250
  label: Image
- name: ingredients
  type: field_group_list
  fields:
  - name: name
    type: text
    config:
      required: true
    label: Name
  - name: quantity
    type: text
    config:
      required: true
    label: Quantity
  - name: notes
    type: text
    config:
      required: false
    label: Notes
  - name: image
    type: file
    config:
      maxSize: 250
    label: Image
  config:
    min: 
    max: 
    labelField: 
  label: Ingredients
- name: process
  type: field_group_list
  fields:
  - name: title
    type: text
    config:
      required: false
    label: Title
  - name: description
    type: textarea
    default: ''
    config:
      required: false
      wysiwyg: false
      schema:
        format: markdown
    label: Description
  - name: image
    type: image_gallery
    config: {}
    label: Image
  - name: time
    type: text
    config:
      required: false
    label: Time
  config:
    min: 
    max: 
    labelField: 
  label: Process
pages:
- _posts/bagels.md
- _posts/insalata-di-tonno.md
- _posts/pane.md
- _posts/pizza.md
- _posts/lenticchie-piccanti.md
