---
label: Recipe
hide_body: true
display_field: title
fields:
- name: layout
  type: select
  default: Recipe
  config:
    required: true
    options:
    - Post
    - Recipe
    source:
      type: simple
      section: 
      file: 
      path: 
  label: Layout
- name: title
  type: text
  config:
    required: true
  label: Title
- name: description
  type: textarea
  default: ''
  config:
    required: true
    wysiwyg: false
    schema:
      format: markdown
  label: Description
- name: ingredients
  type: list
  config:
    use_select: false
    min: 
    max: 
  label: Ingredients
- name: process
  type: blocks
  label: Process
  template_types:
  - process
  config:
    min: 
    max: 
